### ISSUE TITLE
[META] Translate Tracking ( Working in progress )

### ISSUE THREAD

**Issue by Kimbyeoungjang** [Kimbyeoungjang/fs2020-translate-to-kor#1]
- **Aircraft**

- [x] asobo-aircraft-208b-grand-caravan-ex
- [x] asobo-aircraft-a320-neo
- [x] asobo-aircraft-b7478i
- [x] asobo-aircraft-bonanza-g36
- [x] asobo-aircraft-c152
- [x] asobo-aircraft-c172sp-as1000
- [x] asobo-aircraft-cap10c
- [x] asobo-aircraft-cj4
- [x] asobo-aircraft-da40-ng
- [x] asobo-aircraft-da62
- [x] asobo-aircraft-dr400
- [x] asobo-aircraft-e330
- [x] asobo-aircraft-flightdesignct
- [x] asobo-aircraft-icon
- [x] asobo-aircraft-kingair350
- [x] asobo-aircraft-orbis
- [x] asobo-aircraft-pitts
- [x] asobo-aircraft-savage-cub
- [x] asobo-aircraft-tbm930
- [x] asobo-aircraft-vl3
- [x] asobo-aircraft-xcub

- **Base**

- [ ] #4 
- [x] fs-base-ui-vr

- **Bush Trip**

- [ ] asobo-bushtrip-alaska
- [ ] asobo-bushtrip-balkans
- [ ] asobo-bushtrip-chile
- [ ] asobo-bushtrip-france
- [ ] asobo-bushtrip-nevada
- [ ] asobo-bushtrip-denmark
- [ ] asobo-bushtrip-finland
- [ ] asobo-bushtrip-iceland
- [ ] asobo-bushtrip-norway
- [ ] asobo-bushtrip-sweden
- [ ] microsoft-bushtrip-austria
- [ ] microsoft-bushtrip-germany
- [ ] microsoft-bushtrip-grandalpine
- [ ] microsoft-bushtrip-swiss

- **Discovery**

- [x] asobo-discovery
- [x] microsoft-discovery-berlin
- [x] microsoft-discovery-pennine

- **Etc**

- [x] asobo-freeflights
- [x] asobo-liveevent

- **Flight Tutorials**

- [ ] asobo-flight-tutorials-a320landing
- [ ] asobo-flight-tutorials-a320takeoff
- [ ] asobo-flight-tutorials-aircraft
- [ ] asobo-flight-tutorials-arrival
- [ ] asobo-flight-tutorials-attitudespitch
- [ ] asobo-flight-tutorials-attitudestest
- [ ] asobo-flight-tutorials-deadreckoning
- [ ] asobo-flight-tutorials-default
- [ ] asobo-flight-tutorials-departure
- [ ] asobo-flight-tutorials-downwind
- [ ] asobo-flight-tutorials-familiarisationflight
- [ ] asobo-flight-tutorials-firstnavigationsolonew
- [ ] asobo-flight-tutorials-firstsoloflightpattern
- [ ] asobo-flight-tutorials-landingdeadstick
- [ ] asobo-flight-tutorials-landingelevator
- [ ] asobo-flight-tutorials-landmarknavigation
- [ ] asobo-flight-tutorials-newbasic
- [ ] asobo-flight-tutorials-newlanding
- [ ] asobo-flight-tutorials-newtakeoff
- [ ] asobo-flight-tutorials-powersettings
- [ ] asobo-flight-tutorials-straightandlevelflight
- [ ] asobo-flight-tutorials-taxi
- [ ] asobo-flight-tutorials-turns

- **Landing Challenge**

- [x] asobo-landingchallenge-cytz-billy-bishop
- [x] asobo-landingchallenge-eg78-outskerries
- [x] asobo-landingchallenge-eghi-southampton
- [x] asobo-landingchallenge-eidl-donegal
- [x] asobo-landingchallenge-kase-aspen
- [x] asobo-landingchallenge-keb-nanwalek
- [x] asobo-landingchallenge-kjac-jackson
- [x] asobo-landingchallenge-ksez-sedona
- [x] asobo-landingchallenge-kswf-stewartintl
- [x] asobo-landingchallenge-lflj-courchevel
- [x] asobo-landingchallenge-lfmn-nice
- [x] asobo-landingchallenge-lowi-innsbruck
- [x] asobo-landingchallenge-lpma-madeira
- [x] asobo-landingchallenge-lxgb-gibraltar
- [x] asobo-landingchallenge-mhtg-toncontin
- [x] asobo-landingchallenge-mynn-nassau
- [x] asobo-landingchallenge-nzqn-queenstown
- [x] asobo-landingchallenge-rjth-hachijojima
- [x] asobo-landingchallenge-rjx8-suwanosejima
- [x] asobo-landingchallenge-rokr-kerama
- [x] asobo-landingchallenge-sbgl-riodejaneiro
- [x] asobo-landingchallenge-scld-llanadagrande
- [x] asobo-landingchallenge-seqm-mariscal-sucre-quito
- [x] asobo-landingchallenge-tffj-gustaf
- [x] asobo-landingchallenge-tncs-saba
- [x] asobo-landingchallenge-vnlk-lukla
- [x] asobo-landingchallenge-vqpr-paro
- [x] asobo-landingchallenge-wx53-bugalaga
- [x] asobo-landingchallenge-yssy-sydney
- [x] asobo-landingchallenge-biis-isafjordur
- [x] asobo-landingchallenge-efva-vaasa
- [x] asobo-landingchallenge-ekrn-bornholm
- [x] asobo-landingchallenge-ensb-svalbard
- [x] asobo-landingchallenge-essa-arlanda
- [x] microsoft-landingchallenge-eddl-dusseldorf
- [x] microsoft-landingchallenge-edxh-duene
- [x] microsoft-landingchallenge-lowk-klagefurt
- [x] microsoft-landingchallenge-lsza-lugano
- [x] microsoft-landingchallenge-lszr-stgallen
