### ISSUE TITLE
[META] Fs-Base Progress

### ISSUE THREAD

**Issue by Kimbyeoungjang** [Kimbyeoungjang/fs2020-translate-to-kor#4]
- [x] ACHIEVEMENT
- [x] AIRCRAFT
- [x] ASSISTANCE
- [x] Badge_Binding_CheckFailed
- [ ] CLUE
- [ ] COCKPIT
- [x] CONTROL
- [x] Country_FAUNA
- [x] FEEDBACK
- [x] FLYING
- [ ] GAME
- [ ] INPUT
- [ ] Language
- [x] Loading
- [ ] Location
- [x] MARKETPLACE
- [ ] MENU
- [ ] MISSION
- [ ] Mission Message
- [ ] ONBOARDING
- [ ] Plane Reward Speaker
- [ ] STATS
- [x] en-US Structure
